### ISSUE TITLE
Support for template literals?

### ISSUE THREAD

**Issue by ysm-dev** [vinicoder/tw-to-css#1]
Thank you for such a great library! 

It would be great if it supports Template Literals.

```jsx
<div style={twj`mx-auto rounded``}></div>
```

cc: https://twind.dev/handbook/styling-with-twind.html

**Comment by ysm-dev** [comment]
@vinicoder Wow, Thank you for the quick feedback and update!

Unfortunately, We decided to use https://twind.style/

But again thank you for the great work!

**Comment by vinicoder** [comment]
No worries, @ysm-dev! I really appreciate your feedback. Regardless, you made a great choice. The idea of this package is to make it possible to use Tailwind in complex places like emails, server-side, and even mobile (with some improvements in mind).

**Comment by ysm-dev** [comment]
@vinicoder Yeah I know, I came from this PR: https://github.com/resendlabs/react-email/pull/382

We are really enjoying using react-email!
