### ISSUE TITLE
Update Tailwind version to v3.3

### ISSUE THREAD

**Issue by vinicoder** [vinicoder/tw-to-css#3]
A new version of Tailwind has been released (https://tailwindcss.com/blog/tailwindcss-v3-3). So we can upgrade to get the benefits.

**Comment by moroshko** [comment]
@vinicoder Any update on this? Would be great to keep up to date!

**Comment by vinicoder** [comment]
Hi @moroshko, apologies for the delay in updates. Finding time can be challenging as a working father of two young children. But I plan to update the package soon.

**Comment by martinez-hugo** [comment]
This is a PR which fix that : https://github.com/vinicoder/tw-to-css/pull/12
